### ISSUE TITLE
The methods for saving the Lightning-Attention model

### ISSUE THREAD

**Issue by wsleepybear** [OpenNLPLab/lightning-attention#10]
I am using `torch.save` to save a model that contains the `lightning_attn_func` function. It seems that the model does not save the parameters related to `lightning_attn_func`. When I reload the model, I find that the results are inconsistent with those during the training process. Is this because the save method is incorrect, or is it for some reason that the save cannot be performed?

**Comment by Doraemonzzz** [comment]
Hello, do you solve it? `lightning_attn_func` is a pure function and does not have any paramters.
