### ISSUE TITLE
No-decay unusable

### ISSUE THREAD

**Issue by jmercat** [OpenNLPLab/lightning-attention#11]
There is a new [no decay](https://github.com/OpenNLPLab/lightning-attention/blob/e0bea8ef49858fc61cda0cb6e17b6b99b92ce1f9/lightning_attn/ops/lightning_attn_interface.py#L5C38-L5C62) function. It is used [here](https://github.com/OpenNLPLab/lightning-attention/blob/e0bea8ef49858fc61cda0cb6e17b6b99b92ce1f9/lightning_attn/ops/lightning_attn_interface.py#L54) but its use is prevented [there](https://github.com/OpenNLPLab/lightning-attention/blob/e0bea8ef49858fc61cda0cb6e17b6b99b92ce1f9/lightning_attn/ops/lightning_attn_interface.py#L17). Should that last assert statement be removed?

**Comment by Doraemonzzz** [comment]
Yes, I'll update this later.

**Comment by Doraemonzzz** [comment]
Update this.
