### ISSUE TITLE
question about benchmark

### ISSUE THREAD

**Issue by Nalilik** [OpenNLPLab/lightning-attention#13]
![bcm](https://github.com/OpenNLPLab/lightning-attention/assets/35440246/2caea3d7-4fcb-48be-a022-c7014edbccaf)
May I ask what's the difference between block 1 and block 3?

**Comment by Doraemonzzz** [comment]
This is a typo; the latter refers to the memory cost. I will update this part later.

**Comment by Doraemonzzz** [comment]
Fix this.
