### ISSUE TITLE
Is lightning attention always working in a causal manner?

### ISSUE THREAD

**Issue by Leopold2333** [OpenNLPLab/lightning-attention#14]
Hi! If I want to use linear attention without causality, is it still better to use lightning attention? Or, simply writing pytorch scripts is OK enough?

**Comment by Doraemonzzz** [comment]
For non-causal scenarios, torch is enough because the computation only involves two matrix multiplications.

**Comment by Leopold2333** [comment]
get it, thank you!

**Comment by kangyiyang** [comment]
For non-causal lightning attenuation, directly using matrix multiplication in PyTorch can lead to excessive memory usage. Are there any alternative methods that could be more suitable?

**Comment by Doraemonzzz** [comment]
For non-causal scenarios, can you provide pseudocode for implementation?
