### ISSUE TITLE
No module named 'lightning_attn'

### ISSUE THREAD

**Issue by EddieEduardo** [OpenNLPLab/lightning-attention#2]
Great work！

After intsalling the module using 'pip install lightning_attn', it still raises an error of 'No module named 'lightning_attn'.

But it indeed has existed in my env.

![1705653265232](https://github.com/OpenNLPLab/lightning-attention/assets/46192067/0fb3c92d-39b6-435d-8f94-02f94f968854)

![1705653370009](https://github.com/OpenNLPLab/lightning-attention/assets/46192067/47eb0d1f-1381-4103-bc0d-28726c3815d8)

Weird...

Needing help, thank you in advance!

**Comment by EddieEduardo** [comment]
If I use the repo to run the codes, this error is gone, but another new issue appear as follows
![1705653581325](https://github.com/OpenNLPLab/lightning-attention/assets/46192067/de1cf923-6ad8-4748-b448-33e7a774ffb6)
The process is stuck here.

**Comment by EddieEduardo** [comment]
If I use the repo to run the codes, this error is gone, but another new issue appears as follows
![1705653701431](https://github.com/OpenNLPLab/lightning-attention/assets/46192067/acde3b37-01f1-4cec-bfed-6cfa5b583933)
The process is stuck here.

**Comment by Doraemonzzz** [comment]
> If I use the repo to run the codes, this error is gone, but another new issue appears as follows ![1705653701431](https://private-user-images.githubusercontent.com/46192067/298004363-acde3b37-01f1-4cec-bfed-6cfa5b583933.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTQwOTksIm5iZiI6MTcwNTY1Mzc5OSwicGF0aCI6Ii80NjE5MjA2Ny8yOTgwMDQzNjMtYWNkZTNiMzctMDFmMS00Y2VjLWJmZWQtNmNmYTViNTgzOTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA4NDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMzgzMmViYTY5OTFkZDI1MGM5ZjYwYWE3ZjVkMjA0ZTQ2MjI4NjUwMjkzMWY5ODg1OTUyNWI4YmIwN2ViMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dJqdhjeeYcU7JJTaUvDjm4jtzPnBYsGsbxgwduVZvoU) The process is stuck here.

Hello, could you show the versions of torch and cuda?

**Comment by EddieEduardo** [comment]
Hi, thanks for replying.

![1705654351665](https://github.com/OpenNLPLab/lightning-attention/assets/46192067/b043cd80-de08-4fe0-a2de-1b6fc778a646)

cuda version 11.4

**Comment by Doraemonzzz** [comment]
Would you mid do the following command:
```
pip list | grep triton
```
The repo depends on triton and tirton-nightly, you shoud run the following command:
```
pip install triton==2.0.0
pip install triton-nightly==2.1.0.dev20230728172942 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/
```

**Comment by Doraemonzzz** [comment]
> Hi, good evening! The version of triton is 2.0.0 ![1705670001773](https://private-user-images.githubusercontent.com/46192067/298078617-67d2a6c0-f5e1-4b7a-8ff3-5ba151a0f996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzA0NTIsIm5iZiI6MTcwNTY3MDE1MiwicGF0aCI6Ii80NjE5MjA2Ny8yOTgwNzg2MTctNjdkMmE2YzAtZjVlMS00YjdhLThmZjMtNWJhMTUxYTBmOTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDEzMTU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MjRlNzFkMDhlZGU3NjdlNjU3ZmQ5ZWQ4OTJjMjZjZjYxNWY0MmNjNDE1ZWVkYzRhNzYwNjBhZWIyYmUzNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YUbCaHOF_rIPgd3gLX6MiOXjxAju9T9MLfbXl6OnHdQ) Do I need to 'pip install triton-nightly==2.1.0.dev20230728172942 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/' ?

Yes, this repo depends on triton-nightly.

**Comment by EddieEduardo** [comment]
Hi, it worked!!!! Thank you a looooot!!!
But 
dtype = torch.bfloat16
**device = torch.device("cuda")**
% device = torch.device("cuda:1")
b, h, n, d, e = 2, 12, 2048, 64, 64

q = torch.randn((b, h, n, d), dtype=dtype, device=device).requires_grad_()
k = torch.randn((b, h, n, d), dtype=dtype, device=device).requires_grad_()
v = torch.randn((b, h, n, e), dtype=dtype, device=device).requires_grad_()
s = _build_slope_tensor(h).to(q.device).to(torch.float32)

**When I assign the model and tensor on a specific gpu using **_'device = torch.device("cuda:1")'_**, another error will occur as follows:**
Traceback (most recent call last):
  File "....../lightning-attention-main/info_registration1.py", line 28, in <module>
    o = lightning_attn_func(q, k, v, s)
  File "....../lightning-attention-main/lightning_attn/ops/lightning_attn_interface.py", line 25, in lightning_attn_func
    o += lightning_attn2(q1, k1, v, s)
  File "....../lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "....../lightning-attention-main/lightning_attn/ops/triton/lightning_attn2.py", line 416, in forward
    _fwd_kernel[grid](
  File "<string>", line 65, in _fwd_kernel
  File "....../lib/python3.10/site-packages/triton/compiler/compiler.py", line 579, in __getattribute__
    self._init_handles()
  File "....../lib/python3.10/site-packages/triton/compiler/compiler.py", line 570, in _init_handles
    mod, func, n_regs, n_spills = fn_load_binary(self.metadata["name"], self.asm[bin_path], self.shared, device)
RuntimeError: Triton Error [CUDA]: context is destroyed


o = lightning_attn_func(q, k, v, s)

print(o.shape)

**Comment by EddieEduardo** [comment]
> device = torch.device("cuda")

Using device = torch.device("cuda") is fine without any errors.

**Comment by XintianHan** [comment]
> > Great work！
> > After intsalling the module using 'pip install lightning_attn', it still raises an error of 'No module named 'lightning_attn'.
> > But it indeed has existed in my env.
> > ![1705653265232](https://private-user-images.githubusercontent.com/46192067/298002513-0fb3c92d-39b6-435d-8f94-02f94f968854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTQwOTksIm5iZiI6MTcwNTY1Mzc5OSwicGF0aCI6Ii80NjE5MjA2Ny8yOTgwMDI1MTMtMGZiM2M5MmQtMzliNi00MzVkLThmOTQtMDJmOTRmOTY4ODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA4NDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiOWU5MGU3NDJhMWY1NmY3NTI4MzE0ZDgwMGVkOWY5YjNkNWNhODNhZTNkYmNhYmFjZjY0MmRmNjg3Nzg1ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0l3MTAGlnddCNP60hx9xKmlVKCGaWOwEaRzKWOOP3DM)
> > ![1705653370009](https://private-user-images.githubusercontent.com/46192067/298002931-47eb0d1f-1381-4103-bc0d-28726c3815d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTQwOTksIm5iZiI6MTcwNTY1Mzc5OSwicGF0aCI6Ii80NjE5MjA2Ny8yOTgwMDI5MzEtNDdlYjBkMWYtMTM4MS00MTAzLWJjMGQtMjg3MjZjMzgxNWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA4NDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YmNjM2UyMzZiMjVjZmFhYmZlNmI1ZGIwYzQyYWRiYzM2MDJjYmFmODQxYWRmMDJlNjMxZTU2YWI2ZTE1ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bmS5VR1f_fYmyrmM6qIckLbSakgWyYYKr7_ctgDJiIo)
> > Weird...
> > Needing help, thank you in advance!
> 
> It seems that I forget to upload the package to pypi, I'll solve this as soon as possible.

Did you update this? I still have the same error.

**Comment by Doraemonzzz** [comment]
I

> > > Great work！
> > > After intsalling the module using 'pip install lightning_attn', it still raises an error of 'No module named 'lightning_attn'.
> > > But it indeed has existed in my env.
> > > ![1705653265232](https://private-user-images.githubusercontent.com/46192067/298002513-0fb3c92d-39b6-435d-8f94-02f94f968854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTQwOTksIm5iZiI6MTcwNTY1Mzc5OSwicGF0aCI6Ii80NjE5MjA2Ny8yOTgwMDI1MTMtMGZiM2M5MmQtMzliNi00MzVkLThmOTQtMDJmOTRmOTY4ODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA4NDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiOWU5MGU3NDJhMWY1NmY3NTI4MzE0ZDgwMGVkOWY5YjNkNWNhODNhZTNkYmNhYmFjZjY0MmRmNjg3Nzg1ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0l3MTAGlnddCNP60hx9xKmlVKCGaWOwEaRzKWOOP3DM)
> > > ![1705653370009](https://private-user-images.githubusercontent.com/46192067/298002931-47eb0d1f-1381-4103-bc0d-28726c3815d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTQwOTksIm5iZiI6MTcwNTY1Mzc5OSwicGF0aCI6Ii80NjE5MjA2Ny8yOTgwMDI5MzEtNDdlYjBkMWYtMTM4MS00MTAzLWJjMGQtMjg3MjZjMzgxNWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA4NDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YmNjM2UyMzZiMjVjZmFhYmZlNmI1ZGIwYzQyYWRiYzM2MDJjYmFmODQxYWRmMDJlNjMxZTU2YWI2ZTE1ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bmS5VR1f_fYmyrmM6qIckLbSakgWyYYKr7_ctgDJiIo)
> > > Weird...
> > > Needing help, thank you in advance!
> > 
> > 
> > It seems that I forget to upload the package to pypi, I'll solve this as soon as possible.
> 
> Did you update this? I still have the same error.

Sorry, I forget to upload the package to pypi. For now, you can use the following command to install:
```
git clone https://github.com/OpenNLPLab/lightning-attention.git
pip install -e .
```
